# Generated by Django 5.0 on 2024-01-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='aboutus_img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
